language: python
python:
  - "2.7"
  - "3.4"

#command to install dependencies
install: "pip install -r requirements.txt"
#command to run tests
script: python app/manage.py test

notifications:
  email:
  - ljimenez@stancedata.com
  - vguillen@stancedata.com
  slack:
    rooms:
      - secure: "WU5fe+rvbzHE3nmmKGlTp6YkNoQOUTNtBUB82hd/94nvFz/q0hT6Zs+N2e4yKLBw9tkslNcSwYRJHzwlx96sugacbsVKFtb5/rVY5x3xca19vSehy6UUgd8s+fH05GGlr1YJgzMJ5Z5GYJFEfZ1FdcWv2qhSwGdHpEEbzGxGL9k="
