language: python
python:
  - "2.7"
  - "3.4"

#command to install dependencies
install: "pip install -r requirements.txt"
#command to run tests
script: python app/manage.py test

notifications:
  email:
  - ljimenez@stancedata.com
  - vguillen@stancedata.com
  secure: "qKn3Wfm3w7e1IkWQ5MW2nCNett4krVVdpzuhrcQhkeCSxvSouJrqbDsGBPEtZrDlIPZgUVUfDvNUVDJX7QTCJQYJ7pg81J8EsIxGAApUHcuFElP70Z71Wy5hM7+B17IptqP5KMznrfXpzq0fQHXJKlPgh6Y25yNtYrUdIL7cr5c="
